/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/me/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Preferences */
        get: operations["get_preferences_api_v1_me_preferences_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Preferences */
        patch: operations["update_preferences_api_v1_me_preferences_patch"];
        trace?: never;
    };
    "/api/v1/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Notifications */
        get: operations["list_notifications_api_v1_notifications_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/{notification_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Notification */
        patch: operations["update_notification_api_v1_notifications__notification_id__patch"];
        trace?: never;
    };
    "/api/v1/watches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Watches */
        get: operations["list_watches_api_v1_watches_get"];
        put?: never;
        /** Create Watch */
        post: operations["create_watch_api_v1_watches_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/watches/{watch_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Watch */
        get: operations["get_watch_api_v1_watches__watch_id__get"];
        put?: never;
        post?: never;
        /** Delete Watch */
        delete: operations["delete_watch_api_v1_watches__watch_id__delete"];
        options?: never;
        head?: never;
        /** Update Watch */
        patch: operations["update_watch_api_v1_watches__watch_id__patch"];
        trace?: never;
    };
    "/api/v1/watches/{watch_id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Watch History */
        get: operations["watch_history_api_v1_watches__watch_id__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/webhooks/bright-data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Bright Data Webhook */
        post: operations["bright_data_webhook_api_v1_webhooks_bright_data_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/webhooks/clerk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Clerk Webhook */
        post: operations["clerk_webhook_api_v1_webhooks_clerk_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AlertState
         * @enum {string}
         */
        AlertState: "armed" | "triggered";
        /**
         * AvailabilityStatus
         * @enum {string}
         */
        AvailabilityStatus: "unknown" | "in_stock" | "out_of_stock" | "unavailable";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * NotificationChannel
         * @enum {string}
         */
        NotificationChannel: "email" | "in_app";
        /** NotificationResponse */
        NotificationResponse: {
            channel: components["schemas"]["NotificationChannel"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /** Read At */
            read_at: string | null;
            /** Sent At */
            sent_at: string | null;
            status: components["schemas"]["NotificationStatus"];
        };
        /**
         * NotificationStatus
         * @enum {string}
         */
        NotificationStatus: "pending" | "sending" | "sent" | "failed";
        /** NotificationUpdate */
        NotificationUpdate: {
            /** Read */
            read: boolean;
        };
        /** PriceObservationResponse */
        PriceObservationResponse: {
            availability: components["schemas"]["AvailabilityStatus"];
            /** Currency */
            currency: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Item Price Minor */
            item_price_minor: number;
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
            /** Price Minor */
            price_minor: number;
            /** Shipping Price Minor */
            shipping_price_minor: number;
        };
        /** ProductResponse */
        ProductResponse: {
            availability: components["schemas"]["AvailabilityStatus"];
            /** Canonical Url */
            canonical_url: string;
            /** Currency */
            currency: string | null;
            /** Current Price Minor */
            current_price_minor: number | null;
            /** External Id */
            external_id: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Image Url */
            image_url: string | null;
            /** Item Price Minor */
            item_price_minor: number | null;
            /** Last Checked At */
            last_checked_at: string | null;
            /** Region */
            region: string;
            /** Shipping Price Minor */
            shipping_price_minor: number | null;
            store: components["schemas"]["Store"];
            /** Title */
            title: string | null;
        };
        /**
         * Store
         * @enum {string}
         */
        Store: "amazon" | "ebay";
        /** UserPreferencesResponse */
        UserPreferencesResponse: {
            /**
             * Alert Rearm Percent
             * @default 3
             */
            alert_rearm_percent: number;
            /** Email */
            email?: string | null;
            /**
             * Email Enabled
             * @default true
             */
            email_enabled: boolean;
        };
        /** UserPreferencesUpdate */
        UserPreferencesUpdate: {
            /** Alert Rearm Percent */
            alert_rearm_percent?: number | null;
            /** Email Enabled */
            email_enabled?: boolean | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WatchCreate */
        WatchCreate: {
            /** Currency */
            currency: string;
            /**
             * Notify Back In Stock
             * @default true
             */
            notify_back_in_stock: boolean;
            /**
             * Notify Initial Below Target
             * @default true
             */
            notify_initial_below_target: boolean;
            /** Target Price Minor */
            target_price_minor: number;
            /** Url */
            url: string;
        };
        /** WatchResponse */
        WatchResponse: {
            alert_state: components["schemas"]["AlertState"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Currency */
            currency: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Notify Back In Stock */
            notify_back_in_stock: boolean;
            /** Notify Initial Below Target */
            notify_initial_below_target: boolean;
            product: components["schemas"]["ProductResponse"];
            status: components["schemas"]["WatchStatus"];
            /** Target Price Minor */
            target_price_minor: number;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * WatchStatus
         * @enum {string}
         */
        WatchStatus: "active" | "paused";
        /** WatchUpdate */
        WatchUpdate: {
            /** Notify Back In Stock */
            notify_back_in_stock?: boolean | null;
            /** Notify Initial Below Target */
            notify_initial_below_target?: boolean | null;
            status?: components["schemas"]["WatchStatus"] | null;
            /** Target Price Minor */
            target_price_minor?: number | null;
        };
        /** WebhookAccepted */
        WebhookAccepted: {
            /**
             * Accepted
             * @default true
             */
            accepted: boolean;
            /**
             * Duplicate
             * @default false
             */
            duplicate: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_preferences_api_v1_me_preferences_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPreferencesResponse"];
                };
            };
        };
    };
    update_preferences_api_v1_me_preferences_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserPreferencesUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPreferencesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_notifications_api_v1_notifications_get: {
        parameters: {
            query?: {
                unread_only?: boolean;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_notification_api_v1_notifications__notification_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notification_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NotificationUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_watches_api_v1_watches_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["WatchStatus"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_watch_api_v1_watches_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatchCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_watch_api_v1_watches__watch_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                watch_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_watch_api_v1_watches__watch_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                watch_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_watch_api_v1_watches__watch_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                watch_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatchUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    watch_history_api_v1_watches__watch_id__history_get: {
        parameters: {
            query?: {
                limit?: number;
                range?: "7d" | "30d" | "90d" | "all";
            };
            header?: never;
            path: {
                watch_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PriceObservationResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bright_data_webhook_api_v1_webhooks_bright_data_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookAccepted"];
                };
            };
        };
    };
    clerk_webhook_api_v1_webhooks_clerk_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookAccepted"];
                };
            };
        };
    };
}
