// Generated by `pnpm generate:marketplaces` from docs/marketplaces.json.
// Do not edit by hand: the supported hosts are defined once, in the API's store
// adapters (apps/api/app/providers/adapters.py). Editing here would let the
// browser accept URLs the API rejects. Regenerate instead.

export type SupportedMarketplace = "amazon" | "ebay";

export interface MarketplaceHostRules {
  readonly domains: readonly string[];
  readonly hostPrefixes: readonly string[];
}

export const MARKETPLACES: Readonly<Record<SupportedMarketplace, MarketplaceHostRules>> = {
  "amazon": {
    domains: ["amazon.ae", "amazon.ca", "amazon.co.jp", "amazon.co.uk", "amazon.com", "amazon.com.au", "amazon.com.br", "amazon.com.mx", "amazon.de", "amazon.es", "amazon.fr", "amazon.in", "amazon.it", "amazon.nl", "amazon.pl", "amazon.sa", "amazon.se", "amazon.sg"],
    hostPrefixes: ["www.", "smile.", "m."]
  },
  "ebay": {
    domains: ["ebay.at", "ebay.be", "ebay.ca", "ebay.ch", "ebay.co.uk", "ebay.com", "ebay.com.au", "ebay.com.sg", "ebay.de", "ebay.es", "ebay.fr", "ebay.ie", "ebay.it", "ebay.nl", "ebay.pl"],
    hostPrefixes: ["www.", "m."]
  }
} as const;

export const SUPPORTED_MARKETPLACES = Object.keys(MARKETPLACES) as SupportedMarketplace[];
