"""Add back-in-stock alerts.

Adds the per-watch ``notify_back_in_stock`` flag. The new ``back_in_stock``
``AlertKind`` value needs no schema change: like every enum in this codebase,
``alerts.kind`` is a non-native ``Enum`` (``create_constraint`` defaults to
False), so it is a plain ``varchar(20)`` with no CHECK constraint, and
``back_in_stock`` (13 chars) fits the existing width.

Revision ID: 0002_back_in_stock
Revises: 0001_initial
Create Date: 2026-07-22
"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0002_back_in_stock"
down_revision: str | None = "0001_initial"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Backfill existing watches to ON (the model default), then drop the server
    # default so the column matches the autogenerated model metadata.
    op.add_column(
        "watches",
        sa.Column(
            "notify_back_in_stock",
            sa.Boolean(),
            nullable=False,
            server_default=sa.true(),
        ),
    )
    op.alter_column("watches", "notify_back_in_stock", server_default=None)


def downgrade() -> None:
    op.drop_column("watches", "notify_back_in_stock")
